### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by friedroman** [brayniac/tic#64]
Hi. Just wanted to poke and ask if there are any plans to support windows. Right now the clocksource crate is not compiling due to libc get_time and friends functions not present. As far as I can see this is the only problem so replacing it with something equivalent from winapi might allow it to work.

**Comment by brayniac** [comment]
Hi @friedroman thanks for raising this issue. I think adding Windows support to `clocksource` is possible; however, I'm not as familiar with systems programming on Windows. I've cut an issue on `clocksource` repo for Windows support. I will leave this issue open until that is addressed. PRs welcome to help add Windows support. =)

**Comment by brayniac** [comment]
tic 0.4.0 is published to crates.io using the clocksource 0.4.0 dependency. This should address windows support. Again, thanks for your contribution, @friedroman
