### ISSUE TITLE
Any way to decouple the window characteristics of running the receive loop from the actual receiving?

### ISSUE THREAD

**Issue by tobz** [brayniac/tic#68]
Sorry for the cryptic title, I had a hard time coming up with a better one.

So I've currently integrated tic into my application, and I'm having a small issue.  Practically speaking, the built-in HTTP server is fine but I was trying to see if I could generate a more tailored output by grabbing the `Meters<T>` data directly.

To do this, I have a dedicated thread that basically receives control messages (like `tic::Receiver` does!) and processes them before running the receiver once via `run_once`.  What I didn't anticipate is that the receiver would continue looping inside `run_once` until `window` time had elapsed.

I was curious if you had ever had thoughts about decoupling the HTTP server and expanding the control plane, so to speak, so that the receiver could be interacted with while it's currently "running."

Tokio, which uses mio, has provisions for a custom polling lane for things aren't baked-in mio `EventedFd`'s, which illustrates the concept of out-of-band operations nicely, I think.

Not really a problem so to speak but I'd be curious on your thoughts.  This would remove the HTTP portion to let people build richer integrations while still cooperating effectively with tic's inherent event loop model.

**Comment by tobz** [comment]
Thinking more about this, it would pave the way for adding plugins/extensions on top of tic, where you could rewrite the HTTP portion as a separate crate, or maybe write it with gRPC! Or a plugin that spoke natively to some sort of metrics aggregation system... or in my case, I'd just use it to talk to tic directly so I could interoperate with it how I wanted. :)

Again, I'd be willing to write a PR for this (including an HTTP subcrate to replace that functionality) but was curious to hear your thoughts!

**Comment by tobz** [comment]
Actually, thinking about this even more.... maybe it would be as simple as a new type that can tap into the existing control plane channel (`control_rx`/`control_tx`, just clone the sender so it can push in commands) and new commands for the operations we might care about, like, "give me a snapshot of the meters".

I think, speed wise, this should be the same if not faster than the current HTTP code because we'd be tapped into the event loop rather than just waiting for our "should we service HTTP yet?" timeout in the inner loop.

**Comment by brayniac** [comment]
@tobz - this would definitely be a smart design improvement. I've been working on a new library for metrics at work. My goal is to OSS it at some point. This is one of the design improvements in the new library - definitely makes sense to decouple the metrics aggregation from exposition/reporting. 

Since I don't have a concrete timeline on releasing that, I'm definitely open to PRs to improve tic in the meantime. Happy to review and merge a PR once we're both happy with it. Thanks!

**Comment by tobz** [comment]
Sounds good!  I have a prototype knocked up that is at least compiling so I'll be able to PR that soon and we can discuss it more.

**Comment by tobz** [comment]
Gonna close this in favor of continuing any discussion in the PR itself: #69
